import { Navbar } from '@/components/Navbar'
import './globals.css'
import { Roboto } from 'next/font/google'
import Provider from '@/components/Provider'
import { ScrollArea } from '@/components/ui/scroll-area'
import { cn } from '@/lib/utils'
import { NextAuthProvider } from '@/components/SessionProvider'
import ProductProvider from '@/context/CartContext'
import { Toaster } from '@/components/ui/toaster'

const roboto = Roboto({
  subsets: ['cyrillic'],
  weight: '400'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(roboto.className, 'overflow-hidden')}>
        <NextAuthProvider>
          <Provider>
            <ProductProvider>
              {children}
              <Toaster />
            </ProductProvider>
          </Provider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
